### PR TITLE
Update Rerun to 0.17

### PR DESCRIPTION
**Pull request by jprochazk**
- https://github.com/rerun-io/rerun/issues/6519

This updates to the latest version of `@rerun-io/web-viewer`, which introduces a fullscreen mode and panel configuration.

This is a draft because `0.17` has not been released yet.

### CODE REVIEW

**Comment by jprochazk** [comment]
`0.17` cannot load any recording from `0.16.1`, so this is currently half-broken

**Comment by radames** [comment]
hi @jprochazk thanks! when should I merge this?

**Comment by jprochazk** [comment]
Hi! We're working on getting an 0.17 release out soon, it'll be ready at that point.

**Comment by radames** [comment]
I see! thanks 🙏

**Comment by jprochazk** [comment]
We released [0.17](https://github.com/rerun-io/rerun/releases/tag/0.17.0) yesterday. I bumped versions, and updated the demo to use a separate viewer per tab.

**Comment by emilk** [comment]
Is this ready to be merged then?

**Comment by jprochazk** [comment]
Yes, it's ready, just needs a review. :)

**Comment by radames** [comment]
Nice ! I'll take a look today! Thanks

**Comment by radames** [comment]
Sorry for the delay here! I'll push to pip soon

**Pull request merged**
